

CREATE TABLE IF NOT EXISTS public.dw_meta_ads_attribution
(
    id serial NOT NULL,
    unique_id character varying(500) COLLATE pg_catalog."default" NOT NULL,
    campaign_id bigint NOT NULL,
    campaign_name text COLLATE pg_catalog."default",
    adset_id bigint,
    adset_name text COLLATE pg_catalog."default",
    ad_id bigint,
    ad_name text COLLATE pg_catalog."default",
    date_start date NOT NULL,
    hour integer NOT NULL,
    hourly_window character varying(50) COLLATE pg_catalog."default",
    impressions integer DEFAULT 0,
    clicks integer DEFAULT 0,
    spend numeric(15, 2) DEFAULT 0.0,
    cpm numeric(15, 4) DEFAULT 0.0,
    cpc numeric(15, 4) DEFAULT 0.0,
    ctr numeric(15, 4) DEFAULT 0.0,
    action_web_in_store_purchase integer DEFAULT 0,
    action_post_engagement integer DEFAULT 0,
    action_onsite_web_view_content integer DEFAULT 0,
    action_onsite_web_add_to_cart integer DEFAULT 0,
    action_offsite_pixel_add_payment_info integer DEFAULT 0,
    action_onsite_web_purchase integer DEFAULT 0,
    action_page_engagement integer DEFAULT 0,
    action_onsite_web_initiate_checkout integer DEFAULT 0,
    action_video_view integer DEFAULT 0,
    action_offsite_pixel_view_content integer DEFAULT 0,
    action_offsite_pixel_add_to_cart integer DEFAULT 0,
    action_offsite_pixel_initiate_checkout integer DEFAULT 0,
    action_offsite_pixel_purchase integer DEFAULT 0,
    action_offsite_meta_leads integer DEFAULT 0,
    action_link_click integer DEFAULT 0,
    action_post_reaction integer DEFAULT 0,
    action_onsite_conversion_messaging_conversation_started_7d integer DEFAULT 0,
    action_onsite_conversion_messaging_block integer DEFAULT 0,
    action_omni_landing_page_view integer DEFAULT 0,
    action_onsite_conversion_post_save integer DEFAULT 0,
    action_landing_page_view integer DEFAULT 0,
    action_onsite_conversion_messaging_first_reply integer DEFAULT 0,
    action_offsite_content_view_add_meta_leads integer DEFAULT 0,
    value_web_in_store_purchase numeric(15, 2) DEFAULT 0.0,
    value_onsite_web_purchase numeric(15, 2) DEFAULT 0.0,
    value_onsite_web_add_to_cart numeric(15, 2) DEFAULT 0.0,
    value_add_to_cart numeric(15, 2) DEFAULT 0.0,
    value_add_payment_info numeric(15, 2) DEFAULT 0.0,
    value_initiate_checkout numeric(15, 2) DEFAULT 0.0,
    value_omni_initiated_checkout numeric(15, 2) DEFAULT 0.0,
    value_offsite_pixel_view_content numeric(15, 2) DEFAULT 0.0,
    value_offsite_pixel_add_to_cart numeric(15, 2) DEFAULT 0.0,
    value_offsite_pixel_initiate_checkout numeric(15, 2) DEFAULT 0.0,
    value_offsite_pixel_purchase numeric(15, 2) DEFAULT 0.0,
    value_onsite_web_view_content numeric(15, 2) DEFAULT 0.0,
    value_onsite_web_app_view_content numeric(15, 2) DEFAULT 0.0,
    value_onsite_web_app_add_to_cart numeric(15, 2) DEFAULT 0.0,
    value_omni_view_content numeric(15, 2) DEFAULT 0.0,
    value_omni_add_to_cart numeric(15, 2) DEFAULT 0.0,
    value_view_content numeric(15, 2) DEFAULT 0.0,
    attributed_orders_count integer DEFAULT 0,
    attributed_orders_revenue numeric(15, 2) DEFAULT 0.0,
    attributed_orders_cogs numeric(15, 2) DEFAULT 0.0,
    attributed_orders_quantity integer DEFAULT 0,
    attributed_orders jsonb,
    product_details jsonb,
    order_ids text COLLATE pg_catalog."default",
    sku_list text COLLATE pg_catalog."default",
    utm_source character varying(100) COLLATE pg_catalog."default",
    utm_medium character varying(100) COLLATE pg_catalog."default",
    utm_campaign character varying(100) COLLATE pg_catalog."default",
    utm_content character varying(100) COLLATE pg_catalog."default",
    utm_term character varying(100) COLLATE pg_catalog."default",
    channel character varying(50) COLLATE pg_catalog."default",
    attribution_source character varying(100) COLLATE pg_catalog."default",
    analysis_date date DEFAULT CURRENT_DATE,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT dw_meta_ads_attribution_pkey PRIMARY KEY (id),
    CONSTRAINT dw_meta_ads_attribution_unique_id_key UNIQUE (unique_id),
    CONSTRAINT unique_meta_campaign_hour UNIQUE (campaign_id, adset_id, ad_id, date_start, hour)
);
END;




-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.dw_google_ads_attribution
(
    id serial NOT NULL,
    unique_id character varying(500) COLLATE pg_catalog."default" NOT NULL,
    campaign_id bigint NOT NULL,
    campaign_name text COLLATE pg_catalog."default",
    customer_id bigint,
    advertising_channel_type character varying(100) COLLATE pg_catalog."default",
    campaign_status character varying(50) COLLATE pg_catalog."default",
    date_start date NOT NULL,
    hour integer NOT NULL,
    hourly_window character varying(50) COLLATE pg_catalog."default",
    impressions bigint DEFAULT 0,
    clicks integer DEFAULT 0,
    cost_micros bigint DEFAULT 0,
    cost_amount numeric(15, 2) DEFAULT 0.0,
    average_cpc_micros bigint DEFAULT 0,
    average_cpc numeric(15, 4) DEFAULT 0.0,
    average_cost_micros bigint DEFAULT 0,
    average_cpm numeric(15, 4) DEFAULT 0.0,
    ctr numeric(15, 4) DEFAULT 0.0,
    interactions integer DEFAULT 0,
    interaction_rate numeric(15, 4) DEFAULT 0.0,
    engagements integer DEFAULT 0,
    engagement_rate numeric(15, 4) DEFAULT 0.0,
    conversions numeric(15, 2) DEFAULT 0.0,
    conversions_value numeric(15, 2) DEFAULT 0.0,
    cost_per_conversion_micros bigint DEFAULT 0,
    cost_per_conversion numeric(15, 4) DEFAULT 0.0,
    all_conversions numeric(15, 2) DEFAULT 0.0,
    all_conversions_value numeric(15, 2) DEFAULT 0.0,
    cost_per_all_conversions_micros bigint DEFAULT 0,
    cost_per_all_conversions numeric(15, 4) DEFAULT 0.0,
    view_through_conversions integer DEFAULT 0,
    attributed_orders_count integer DEFAULT 0,
    attributed_orders_revenue numeric(15, 2) DEFAULT 0.0,
    attributed_orders_cogs numeric(15, 2) DEFAULT 0.0,
    attributed_orders_quantity integer DEFAULT 0,
    attributed_orders jsonb,
    product_details jsonb,
    order_ids text COLLATE pg_catalog."default",
    sku_list text COLLATE pg_catalog."default",
    utm_source character varying(100) COLLATE pg_catalog."default",
    utm_medium character varying(100) COLLATE pg_catalog."default",
    utm_campaign character varying(100) COLLATE pg_catalog."default",
    utm_content character varying(100) COLLATE pg_catalog."default",
    utm_term character varying(100) COLLATE pg_catalog."default",
    channel character varying(50) COLLATE pg_catalog."default",
    attribution_source character varying(100) COLLATE pg_catalog."default",
    analysis_date date DEFAULT CURRENT_DATE,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT dw_google_ads_attribution_pkey PRIMARY KEY (id),
    CONSTRAINT dw_google_ads_attribution_unique_id_key UNIQUE (unique_id),
    CONSTRAINT unique_google_campaign_hour UNIQUE (campaign_id, date_start, hour)
);
END;


-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.dw_organic_attribution
(
    id serial NOT NULL,
    unique_id character varying(500) COLLATE pg_catalog."default" NOT NULL,
    utm_source character varying(100) COLLATE pg_catalog."default",
    utm_medium character varying(100) COLLATE pg_catalog."default",
    utm_campaign character varying(100) COLLATE pg_catalog."default",
    utm_content character varying(100) COLLATE pg_catalog."default",
    utm_term character varying(100) COLLATE pg_catalog."default",
    date_start date,
    hour integer NOT NULL,
    hourly_window character varying(50) COLLATE pg_catalog."default",
    channel character varying(50) COLLATE pg_catalog."default",
    attribution_source character varying(100) COLLATE pg_catalog."default",
    estimated_impressions integer DEFAULT 0,
    estimated_clicks integer DEFAULT 0,
    estimated_spend numeric(15, 2) DEFAULT 0.0,
    attributed_orders_count integer DEFAULT 0,
    attributed_orders_revenue numeric(15, 2) DEFAULT 0.0,
    attributed_orders_cogs numeric(15, 2) DEFAULT 0.0,
    attributed_orders_quantity integer DEFAULT 0,
    attributed_orders jsonb,
    product_details jsonb,
    order_ids text COLLATE pg_catalog."default",
    sku_list text COLLATE pg_catalog."default",
    analysis_date date,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT dw_organic_attribution_pkey PRIMARY KEY (id),
    CONSTRAINT dw_organic_attribution_unique_id_key UNIQUE (unique_id)
);
END;


-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.ads_insights_hourly
(
    campaign_id bigint,
    campaign_name text COLLATE pg_catalog."default",
    adset_id bigint,
    adset_name text COLLATE pg_catalog."default",
    ad_id bigint,
    ad_name text COLLATE pg_catalog."default",
    date_start date,
    date_stop date,
    hourly_window text COLLATE pg_catalog."default",
    impressions bigint,
    clicks bigint,
    spend numeric(18, 2),
    cpm numeric(18, 4),
    cpc numeric(18, 4),
    ctr numeric(18, 4),
    action_web_in_store_purchase bigint,
    action_post_engagement bigint,
    action_onsite_web_view_content bigint,
    action_onsite_web_add_to_cart bigint,
    action_offsite_pixel_add_payment_info bigint,
    action_onsite_web_purchase bigint,
    action_page_engagement bigint,
    action_onsite_web_initiate_checkout bigint,
    action_video_view bigint,
    action_offsite_pixel_view_content bigint,
    action_offsite_pixel_add_to_cart bigint,
    action_offsite_pixel_initiate_checkout bigint,
    action_offsite_pixel_purchase bigint,
    action_offsite_meta_leads bigint,
    action_link_click bigint,
    action_post_reaction bigint,
    value_web_in_store_purchase numeric(18, 2),
    value_onsite_web_purchase numeric(18, 2),
    value_onsite_web_add_to_cart numeric(18, 2),
    value_add_to_cart numeric(18, 2),
    value_add_payment_info numeric(18, 2),
    value_initiate_checkout numeric(18, 2),
    value_omni_initiated_checkout numeric(18, 2),
    value_offsite_pixel_view_content numeric(18, 2),
    value_offsite_pixel_add_to_cart numeric(18, 2),
    value_offsite_pixel_initiate_checkout numeric(18, 2),
    value_offsite_pixel_purchase numeric(18, 2),
    value_onsite_web_view_content numeric(18, 2),
    value_onsite_web_app_view_content numeric(18, 2),
    value_onsite_web_app_add_to_cart numeric(18, 2),
    value_omni_view_content numeric(18, 2),
    value_omni_add_to_cart numeric(18, 2),
    load_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    action_onsite_conversion_messaging_conversation_started_7d bigint,
    action_onsite_conversion_messaging_block bigint,
    action_omni_landing_page_view bigint,
    action_onsite_conversion_post_save bigint,
    action_landing_page_view bigint,
    action_onsite_conversion_messaging_first_reply bigint,
    action_offsite_content_view_add_meta_leads bigint,
    value_view_content numeric(18, 2),
    CONSTRAINT uq_ads_insights_hourly UNIQUE (campaign_id, adset_id, ad_id, date_start, hourly_window)
);
END;



-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.gads_hourly_pmax_campaign_metrics
(
    date date NOT NULL,
    hour smallint NOT NULL,
    customer_id bigint NOT NULL,
    campaign_id bigint NOT NULL,
    campaign_name text COLLATE pg_catalog."default",
    advertising_channel_type text COLLATE pg_catalog."default",
    campaign_status text COLLATE pg_catalog."default",
    clicks bigint,
    ctr double precision,
    cost_micros bigint,
    average_cpc_micros numeric(20, 6),
    average_cost_micros numeric(20, 6),
    interactions bigint,
    interaction_rate double precision,
    engagements bigint,
    engagement_rate double precision,
    conversions numeric(20, 6),
    conversions_value numeric(20, 6),
    cost_per_conversion_micros numeric(20, 6),
    all_conversions numeric(20, 6),
    all_conversions_value numeric(20, 6),
    cost_per_all_conversions_micros numeric(20, 6),
    view_through_conversions bigint,
    CONSTRAINT gads_hourly_pmax_campaign_metrics_pkey PRIMARY KEY (date, hour, customer_id, campaign_id)
);


CREATE TABLE IF NOT EXISTS public.shopify_orders
(
    order_id text COLLATE pg_catalog."default" NOT NULL,
    order_name text COLLATE pg_catalog."default",
    created_at timestamp with time zone,
    processed_at timestamp with time zone,
    updated_at timestamp with time zone,
    closed_at timestamp with time zone,
    cancelled_at timestamp with time zone,
    total_price_amount numeric,
    total_price_currency character(3) COLLATE pg_catalog."default",
    total_shipping_amount numeric,
    total_shipping_currency character(3) COLLATE pg_catalog."default",
    display_fulfillment_status text COLLATE pg_catalog."default",
    ship_city text COLLATE pg_catalog."default",
    ship_province text COLLATE pg_catalog."default",
    ship_country text COLLATE pg_catalog."default",
    customer_referrer_url text COLLATE pg_catalog."default",
    customer_utm_source text COLLATE pg_catalog."default",
    customer_utm_medium text COLLATE pg_catalog."default",
    customer_utm_campaign text COLLATE pg_catalog."default",
    customer_utm_content text COLLATE pg_catalog."default",
    customer_utm_term text COLLATE pg_catalog."default",
    created_at_ist text COLLATE pg_catalog."default",
    processed_at_ist text COLLATE pg_catalog."default",
    updated_at_ist text COLLATE pg_catalog."default",
    closed_at_ist text COLLATE pg_catalog."default",
    cancelled_at_ist text COLLATE pg_catalog."default",
    customer_journey jsonb,
    custom_attributes jsonb,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.customer_details_th
(
    order_id text COLLATE pg_catalog."default" NOT NULL,
    order_name text COLLATE pg_catalog."default",
    created_at timestamp without time zone,
    email character varying(100) COLLATE pg_catalog."default",
    billing_name text COLLATE pg_catalog."default",
    billing_address1 text COLLATE pg_catalog."default",
    billing_address2 text COLLATE pg_catalog."default",
    billing_city text COLLATE pg_catalog."default",
    billing_zip text COLLATE pg_catalog."default",
    billing_province_name text COLLATE pg_catalog."default",
    billing_country text COLLATE pg_catalog."default",
    billing_phone text COLLATE pg_catalog."default",
    shipping_name text COLLATE pg_catalog."default",
    shipping_address1 text COLLATE pg_catalog."default",
    shipping_address2 text COLLATE pg_catalog."default",
    shipping_city text COLLATE pg_catalog."default",
    shipping_zip text COLLATE pg_catalog."default",
    shipping_province_name text COLLATE pg_catalog."default",
    shipping_country text COLLATE pg_catalog."default",
    shipping_phone text COLLATE pg_catalog."default",
    payment_method text COLLATE pg_catalog."default",
    payment_status text COLLATE pg_catalog."default",
    payment_id text COLLATE pg_catalog."default",
    payment_references text COLLATE pg_catalog."default",
    payment_terms_name text COLLATE pg_catalog."default",
    next_payment_due_at timestamp without time zone,
    subtotal numeric(100, 2),
    shipping numeric(100, 2),
    taxes numeric(100, 2),
    discount_amount numeric(100, 2),
    total numeric(100, 2),
    tax_1_name text COLLATE pg_catalog."default",
    tax_1_value numeric(100, 2),
    tax_2_name text COLLATE pg_catalog."default",
    tax_2_value numeric(100, 2),
    notes text COLLATE pg_catalog."default",
    note_attributes text COLLATE pg_catalog."default",
    phone text COLLATE pg_catalog."default",
    fulfillment_status text COLLATE pg_catalog."default",
    line_items jsonb,
    awb_number bigint,
    ewaybill_number text COLLATE pg_catalog."default",
    courier text COLLATE pg_catalog."default",
    shipping_status text COLLATE pg_catalog."default",
    tracking_url text COLLATE pg_catalog."default",
    awb_generated_at timestamp without time zone,
    ewaybill_generated_at timestamp without time zone,
    destination_area text COLLATE pg_catalog."default",
    destination_location text COLLATE pg_catalog."default",
    cluster_code text COLLATE pg_catalog."default",
    bluedart_service_available boolean,
    outstanding_balance numeric(100, 2) DEFAULT 0.00,
    CONSTRAINT customer_details_th_pkey PRIMARY KEY (order_id)
);


CREATE TABLE IF NOT EXISTS public.shopify_order_customer_journey_moments
(
    journey_id serial NOT NULL,
    order_id text COLLATE pg_catalog."default",
    utm_source text COLLATE pg_catalog."default",
    utm_medium text COLLATE pg_catalog."default",
    utm_campaign text COLLATE pg_catalog."default",
    utm_content text COLLATE pg_catalog."default",
    utm_term text COLLATE pg_catalog."default",
    CONSTRAINT shopify_order_customer_journey_moments_pkey PRIMARY KEY (journey_id)
);

CREATE TABLE IF NOT EXISTS public.shopify_order_line_items
(
    item_id text COLLATE pg_catalog."default" NOT NULL,
    order_id text COLLATE pg_catalog."default",
    title text COLLATE pg_catalog."default",
    quantity integer,
    original_unit_price_amount numeric,
    original_unit_price_currency character(3) COLLATE pg_catalog."default",
    discounted_unit_price_amount numeric,
    discounted_unit_price_currency character(3) COLLATE pg_catalog."default",
    variant_id text COLLATE pg_catalog."default",
    CONSTRAINT shopify_order_line_items_pkey PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS public.shopify_product_variants
(
    variant_id text COLLATE pg_catalog."default" NOT NULL,
    variant_title text COLLATE pg_catalog."default",
    sku text COLLATE pg_catalog."default",
    unit_cost_amount numeric,
    unit_cost_currency character(3) COLLATE pg_catalog."default",
    image_url text COLLATE pg_catalog."default",
    image_alt_text text COLLATE pg_catalog."default",
    product_id text COLLATE pg_catalog."default",
    product_title text COLLATE pg_catalog."default",
    vendor text COLLATE pg_catalog."default",
    handle text COLLATE pg_catalog."default",
    selling_price numeric,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT shopify_product_variants_pkey PRIMARY KEY (variant_id)
);

CREATE TABLE IF NOT EXISTS public.product_variant_cost_history
(
    cost_id serial NOT NULL,
    variant_id text COLLATE pg_catalog."default" NOT NULL,
    variant_title text COLLATE pg_catalog."default" NOT NULL,
    sku text COLLATE pg_catalog."default" NOT NULL,
    selling_price numeric NOT NULL,
    unit_cost_amount numeric NOT NULL,
    cost_currency character(3) COLLATE pg_catalog."default" NOT NULL,
    valid_from date NOT NULL,
    valid_to date,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT product_variant_cost_history_pkey PRIMARY KEY (cost_id)
);

CREATE TABLE IF NOT EXISTS public.shopify_line_item_tax_lines
(
    tax_line_id serial NOT NULL,
    item_id text COLLATE pg_catalog."default",
    title text COLLATE pg_catalog."default",
    rate numeric,
    tax_amount numeric,
    tax_currency character(3) COLLATE pg_catalog."default",
    CONSTRAINT shopify_line_item_tax_lines_pkey PRIMARY KEY (tax_line_id)
);





CREATE TABLE IF NOT EXISTS public.amazon_product_metrics_daily
(
    id integer NOT NULL DEFAULT nextval('amazon_product_metrics_daily_id_seq'::regclass),
    campaign_id bigint NOT NULL,
    campaign_name character varying(500) COLLATE pg_catalog."default",
    adgroup_id bigint NOT NULL,
    adgroup_name character varying(500) COLLATE pg_catalog."default",
    product_ad_id bigint,
    asin character varying(20) COLLATE pg_catalog."default",
    sku character varying(100) COLLATE pg_catalog."default",
    date date NOT NULL,
    impressions integer DEFAULT 0,
    clicks integer DEFAULT 0,
    spend numeric(12,2) DEFAULT 0,
    orders integer DEFAULT 0,
    sales numeric(12,2) DEFAULT 0,
    ctr numeric(10,6),
    cpc numeric(10,2),
    acos numeric(10,6),
    roas numeric(10,6),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT amazon_product_metrics_daily_pkey PRIMARY KEY (id),
    CONSTRAINT amazon_product_metrics_daily_campaign_id_adgroup_id_asin_da_key UNIQUE (campaign_id, adgroup_id, asin, date)
)


